### ISSUE TITLE
SQL assignment with a different scenario. In this assignment, we'll focus on multiple tables and the usage of JOIN operations.

### ISSUE THREAD

**Issue by Pankaj-Str** [Pankaj-Str/SQL-tutorial#3]
**Scenario:**
Imagine a database for a university with three tables: `Students`, `Courses`, and `Enrollments`. The tables have the following structures:

- `Students` table:
  - `StudentID` (integer, primary key)
  - `FirstName` (varchar)
  - `LastName` (varchar)
  - `BirthDate` (date)

- `Courses` table:
  - `CourseID` (integer, primary key)
  - `CourseName` (varchar)
  - `Instructor` (varchar)
  - `Credits` (integer)

- `Enrollments` table:
  - `EnrollmentID` (integer, primary key)
  - `StudentID` (integer, foreign key referencing Students table)
  - `CourseID` (integer, foreign key referencing Courses table)
  - `EnrollmentDate` (date)

**Tasks:**

1. **Insert Data:**
   - Insert a new student with the following details:
      - StudentID: 301
      - FirstName: 'Alice'
      - LastName: 'Johnson'
      - BirthDate: '1995-08-15'

2. **Update Data:**
   - Update the instructor of the course with CourseID 201 to 'Professor Smith'.

3. **Delete Data:**
   - Delete all enrollments for the student with StudentID 301.

4. **Query:**
   - Write a SELECT query to retrieve the names of students who have enrolled in the course with CourseID 101, including their course enrollment date.

**Submission Guidelines:**
- Create a SQL script that includes the necessary INSERT, UPDATE, DELETE, and SELECT statements.
- Include comments to explain each statement.
- Assume that the database and tables already exist.

**Sample Solution:**

```sql
-- Task 1: Insert Data
INSERT INTO Students (StudentID, FirstName, LastName, BirthDate)
VALUES (301, 'Alice', 'Johnson', '1995-08-15');

-- Task 2: Update Data
UPDATE Courses
SET Instructor = 'Professor Smith'
WHERE CourseID = 201;

-- Task 3: Delete Data
DELETE FROM Enrollments
WHERE StudentID = 301;

-- Task 4: Query
SELECT Students.FirstName, Students.LastName, Enrollments.EnrollmentDate
FROM Students
JOIN Enrollments ON Students.StudentID = Enrollments.StudentID
WHERE Enrollments.CourseID = 101;
```

**Comment by Prateekmishra0502** [comment]
```sql
-- CREATE A DATABASE 
CREATE DATABASE UNIVERSITY;

-- USE DATABASE
USE UNIVERSITY;

-- CREATE A TABLE 
CREATE TABLE STUDENT(
     StudentID int primary key,
FirstName varchar(40),
LastName varchar(40),
BirthDate date
);
-- STRUCTURE OF THE TABLE
DESC  STUDENT;

-- CREATE A TABLE 
CREATE TABLE COURSE(
      CourseID int primary key,
CourseName varchar(40),
Instructor varchar(40),
Credits int
);

-- CREATE A ANOTHER TABLE
 CREATE TABLE ENROLLMENTS(
      EnrollmentID int primary key,
StudentID int, 
CourseID int,
EnrollmentDate date,
foreign key(StudentID) references STUDENT(StudentID),
foreign key(CourseID) references COURSE(CourseID)
 );
 -- Task 1: Insert Data
INSERT INTO STUDENT (StudentID, FirstName, LastName, BirthDate)
VALUES (301, 'Alice', 'Johnson', '1995-08-15');

Insert INTO COURSE (CourseID,CourseName,Instructor,Credits) 
VALUES(201, 'FULL STACK DEVLOPER', 'ALEX',150000);

INSERT INTO ENROLLMENTS (EnrollmentID,StudentID,CourseID,EnrollmentDate)
VALUES(101, 301,201,'2003-02-05');

-- SHOW THE  TABLE
SELECT * FROM STUDENT;
SELECT * FROM COURSE;
-- Task 2: Update Data
UPDATE COURSE
SET Instructor = 'Professor Smith'
WHERE CourseID = 201;
-- Task 3: Delete Data
DELETE FROM Enrollments
WHERE StudentID = 301;
-- Task 4: Query
SELECT STUDENT.FirstName, STUDENT.LastName, ENROLLMENTS.EnrollmentDate
FROM  STUDENT
JOIN ENROLLMENTS ON STUDENT.StudentID = ENROLLMENTS.StudentID
WHERE ENROLLMENTS.CourseID = 101;
```

**Comment by Calvindefvfdvbg** [comment]
...SQL
-- CREATE A DATABASE 
CREATE DATABASE UNIVERSITY1;
-- USE DATABASE
USE UNIVERSITY1;
-- CREATE A TABLE 
CREATE TABLE STUDENT1(
     StudentID int primary key,
FirstName varchar(20),
LastName varchar(20),
BirthDate date
);
-- STRUCTURE OF THE TABLE
DESC  STUDENT1;
-- CREATE A TABLE 
CREATE TABLE COURSE1(
      CourseID int primary key,
CourseName varchar(40),
Instructor varchar(40),
Credits int
);
-- CREATE A ANOTHER TABLE
 CREATE TABLE ENROLLMENTS1(
      EnrollmentID int primary key,
StudentID int, 
CourseID int,
EnrollmentDate date,
foreign key(StudentID) references STUDENT1(StudentID),
foreign key(CourseID) references COURSE1(CourseID)
 );
-- Task 1: Insert Data
-- Insert a new student with StudentID 301
INSERT INTO Student1 (StudentID, FirstName, LastName, BirthDate)
VALUES (301, 'Alice', 'Johnson', '1995-08-15');

-- Task 2: Update Data
-- Update the instructor of the course with CourseID 201 to 'Professor Smith'
UPDATE Course1
SET Instructor = 'Professor Smith'
WHERE CourseID = 201;

-- Task 3: Delete Data
-- Delete all enrollment records for the student with StudentID 301
DELETE FROM Enrollments1
WHERE StudentID = 301;

-- Task 4: Query
-- Retrieve the names of students enrolled in CourseID 101, including their enrollment date
SELECT 
    S.FirstName, 
    S.LastName, 
    E.EnrollmentDate
FROM 
    Student1 S
