### ISSUE TITLE
this assignment, we'll focus on using the INSERT, UPDATE, and DELETE statements along with the implementation of constraints.

### ISSUE THREAD

**Issue by Pankaj-Str** [Pankaj-Str/SQL-tutorial#4]
**Scenario:**
Consider a database for a music store with two tables: `Albums` and `Artists`. The tables have the following structures:

- `Artists` table:
  - `ArtistID` (integer, primary key)
  - `ArtistName` (varchar)
  - `Genre` (varchar)
  - `Country` (varchar)

- `Albums` table:
  - `AlbumID` (integer, primary key)
  - `AlbumTitle` (varchar)
  - `ReleaseYear` (integer)
  - `ArtistID` (integer, foreign key referencing Artists table)
  - `Price` (numeric)

**Tasks:**

1. **Insert Data:**
   - Insert a new artist with the following details:
      - ArtistID: 101
      - ArtistName: 'Michael Jackson'
      - Genre: 'Pop'
      - Country: 'USA'

   - Insert a new album with the following details:
      - AlbumID: 201
      - AlbumTitle: 'Thriller'
      - ReleaseYear: 1982
      - ArtistID: (Use the ArtistID of Michael Jackson)
      - Price: 19.99

2. **Update Data:**
   - Update the release year of the album with AlbumID 201 to 1984.

3. **Delete Data:**
   - Delete the artist with ArtistID 101 and all albums associated with that artist.

4. **Constraints:**
   - Add a constraint to the `Price` column in the `Albums` table to ensure that the price is greater than or equal to 0.

**Submission Guidelines:**
- Create a SQL script that includes the necessary INSERT, UPDATE, DELETE statements, and the constraint.
- Include comments to explain each statement and describe the purpose of the constraint.
- Assume that the database and tables already exist.

**Sample Solution:**

```sql
-- Task 1: Insert Data
INSERT INTO Artists (ArtistID, ArtistName, Genre, Country)
VALUES (101, 'Michael Jackson', 'Pop', 'USA');

INSERT INTO Albums (AlbumID, AlbumTitle, ReleaseYear, ArtistID, Price)
VALUES (201, 'Thriller', 1982, 101, 19.99);

-- Task 2: Update Data
UPDATE Albums
SET ReleaseYear = 1984
WHERE AlbumID = 201;

-- Task 3: Delete Data
DELETE FROM Albums
WHERE ArtistID = 101;

DELETE FROM Artists
WHERE ArtistID = 101;

-- Task 4: Constraints
ALTER TABLE Albums
ADD CONSTRAINT CHK_PriceNonNegative CHECK (Price >= 0);
```

**Comment by deepanshup123** [comment]
```SQL
-- CREATING THE DATABASE FOR OUR USE 
CREATE DATABASE MUSIC_STORE;

-- USING A DATABASE 
USE MUSIC_STORE;

-- CREATING A TABLE ARTISTS
CREATE TABLE ARTISTS(
	ARTIST_ID INT PRIMARY KEY,
    ARTIST_NAME VARCHAR(50),
    GENERE VARCHAR(20),
    COUNTRY VARCHAR(20)
);

-- TO VIEW OF TABLE
DESC ARTISTS;

-- CREATING A TABLE ALBUM
CREATE TABLE ALBUM(
	ALBUM_ID INT PRIMARY KEY,
    ALBUM_TITLE VARCHAR(50),
    RELEASE_YEAR INT,
    ARTIST_ID INT,
    PRICE NUMERIC,
    FOREIGN KEY (ARTIST_ID) REFERENCES ARTISTS(ARTIST_ID)
);


-- INSERTING THE DATA INTO ARTISTS
INSERT INTO ARTISTS(ARTIST_ID, ARTIST_NAME, GENERE, COUNTRY)
VALUES(101, 'Michael Jackson', 'Pop', 'USA');

-- FOR SEE DATA OF A TABLE
SELECT * FROM ARTISTS;

-- INSERTING THE DATA INTO ALBUM
INSERT INTO ALBUM(ALBUM_ID, ALBUM_TITLE, RELEASE_YEAR, ARTIST_ID, PRICE)
VALUES(201, 'Thriller', 1982, 101, 19.99);

-- FOR SEE DATA OF A TABLE
SELECT * FROM ALBUM;

-- UPDATING THE RELEASE DATE OF ALBUM TABLE
UPDATE ALBUM
SET RELEASE_YEAR = 1984
WHERE ALBUM_ID = 201;

-- DELETING THE DATA FROM ALBUM FIRST BECAUSE ITS LINKED WITH ARTIST TABLE WITH FOREIGN KEY
-- THEN WE CAN'T DELETE FIRST ARTISTS TABLE THAT'S WHY WE DELETE DATA FROM FIRST ALBUM TABLE.
DELETE FROM ALBUM
WHERE ARTIST_ID = 101;

DELETE FROM ARTISTS
WHERE ARTIST_ID = 101;

-- ADDING CONSTRAINTS TO THE CILUMN OF ALBUM 
ALTER TABLE ALBUM
ADD CONSTRAINT PRICE CHECK (PRICE >= 0);
```

**Comment by shital9003** [comment]
```sql
-- Using a  Database
USE shital;

CREATE TABLE Artists (
ArtistID INT PRIMARY KEY,
ArtistName VARCHAR(20),
Genre VARCHAR(10),
Country VARCHAR(10)
);

CREATE TABLE Albums (
AlbumID INT PRIMARY KEY,
AlbumTitle VARCHAR(20),
ReleaseYear INT,
ArtistID INT,
Price NUMERIC,
FOREIGN KEY (ArtistID) REFERENCES Artists(ArtistID)
);

**-- Task 1: Insert Data**

INSERT INTO Artists (ArtistID, ArtistName, Genre, Country)
VALUES (101, "Michael Jackson", "Pop", "USA" );

SELECT *FROM Artists;

INSERT INTO Albums (AlbumID, AlbumTitle, ReleaseYear, ArtistID, Price)
VALUES (201, "Thriller", 1982, 101 , 19.99 );

SELECT *FROM Albums;

**-- Task 2: Update Data**

UPDATE Albums
SET ReleaseYear = 1984
WHERE AlbumID = 201;

SELECT *FROM Albums;

**-- Task 3: Delete Data**

DELETE FROM Albums
WHERE ArtistID = 101;

SELECT *FROM Albums;

DELETE FROM Artists
WHERE ArtistID = 101;

SELECT *FROM Artists;

**-- Task 4: Constraints**

ALTER TABLE Albums
ADD CONSTRAINT Price CHECK (PRICE >= 0);

```

**Comment by Ak-andy** [comment]
''' 
-- creation of database
CREATE DATABASE IF NOT EXISTS company;

-- selecting database
USE company;

-- creating table on temporary basis for current instance and assigning the range to store the values
CREATE TEMPORARY TABLE IF NOT EXISTS Employees (
EmployeeID INT PRIMARY KEY,
FirstName VARCHAR(50),
LastName VARCHAR(50),
Department VARCHAR(25),
Salary NUMERIC);

SELECT * FROM Employees;

-- inseerting values in tables
INSERT INTO Employees VALUES(101,'John','Doe','IT',60000);

-- updatng with setting th limit to update the non of rows
UPDATE  Employees
    SET salary=65000
    WHERE EmployeeID=101
	ORDER BY EmployeeID
    LIMIT 1;

-- deleting specific employee data using employeeID
DELETE FROM Employees
WHERE EmployeeID = 101;
'''

**Comment by Ak-andy** [comment]
,,,
-- creation of database
CREATE DATABASE IF NOT EXISTS company;

-- selecting database
USE company;

-- creating table on temporary basis for current instance and assigning the range to store the values
CREATE TEMPORARY TABLE IF NOT EXISTS Employees (
EmployeeID INT PRIMARY KEY,
FirstName VARCHAR(50),
LastName VARCHAR(50),
Department VARCHAR(25),
Salary NUMERIC);

SELECT * FROM Employees;

-- inseerting values in tables
INSERT INTO Employees VALUES(101,'John','Doe','IT',60000);

-- updatng with setting th limit to update the non of rows
UPDATE  Employees
    SET salary=65000
    WHERE EmployeeID=101
	ORDER BY EmployeeID
    LIMIT 1;

-- deleting specific employee data using employeeID
DELETE FROM Employees
WHERE EmployeeID = 101;
,,,

**Comment by Prateekmishra0502** [comment]
```sql
-- TASK1:CREATE A DATABASE 
CREATE DATABASE MS;

-- TASK2: USE  A DATABASE 
USE MS;

-- TASK3:CREATING A TABLE 
CREATE TABLE ARTISTS(
	ARTIST_ID INT PRIMARY KEY,
    ARTIST_NAME VARCHAR(80),
    GENERE VARCHAR(40),
    COUNTRY VARCHAR(40)
);

-- VIEW THE TABLE STRUCTURE
DESC ARTISTS;

-- CREATING A  ANOTHER TABLE 
CREATE TABLE ALBUM(
	ALBUM_ID INT PRIMARY KEY,
    ALBUM_TITLE VARCHAR(50),
    RELEASE_YEAR INT,
    ARTIST_ID INT,
    PRICE NUMERIC,
    FOREIGN KEY (ARTIST_ID) REFERENCES ARTISTS(ARTIST_ID)
);


-- INSERTING THE DATA INTO ARTISTS TABLE
INSERT INTO ARTISTS(ARTIST_ID, ARTIST_NAME, GENERE, COUNTRY)
VALUES(101, "Michael Jackson", "Pop", "USA");

-- FOR SEE DATA OF A TABLE
  SELECT * FROM ARTISTS;

-- INSERTING THE DATA INTO ALBUM
INSERT INTO ALBUM(ALBUM_ID, ALBUM_TITLE, RELEASE_YEAR, ARTIST_ID, PRICE)
VALUES(201, "Thriller", 1982, 101, 19.99);

--  SEE THE TABLE OF THE DATA
SELECT * FROM ALBUM;

-- UPDATE THE RELEASE DATE IN ALBUM TABLE
UPDATE ALBUM
SET RELEASE_YEAR = 1984
WHERE ALBUM_ID = 201;

-- DELETE THE DATA FROM ALBUM  TABLE FIRST BECAUSE IT IS LINKED WITH ARTIST TABLE WITH FOREIGN KEY
-- SO WE CAN NOT  DELETE FIRST ARTISTS TABLE THAT'S WHY WE DELETE DATA FROM FIRST ALBUM TABLE THEN ARTIST TABLE.
DELETE FROM ALBUM
WHERE ARTIST_ID = 101;

DELETE FROM ARTISTS
WHERE ARTIST_ID = 101;

-- ADD CONSTRAINTS TO THE COLUMN OF ALBUM TABLE
ALTER TABLE ALBUM
ADD CONSTRAINT PRICE CHECK (PRICE >= 0);
```
